#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE "${POSTGRES_RUNTIME_USER}" WITH LOGIN PASSWORD '${POSTGRES_RUNTIME_PASSWORD}';
  GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_RUNTIME_USER}";
  GRANT USAGE ON SCHEMA public TO "${POSTGRES_RUNTIME_USER}";
  ALTER DEFAULT PRIVILEGES FOR ROLE "${POSTGRES_USER}" IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${POSTGRES_RUNTIME_USER}";
  ALTER DEFAULT PRIVILEGES FOR ROLE "${POSTGRES_USER}" IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO "${POSTGRES_RUNTIME_USER}";
EOSQL
